import Foundation

struct BundleBuilder {
    let args: CLIArgs

    func build(iconURL: URL?) throws -> URL {
        let fm = FileManager.default
        let outputDir = URL(fileURLWithPath: args.outputDir)
        let appURL = outputDir.appendingPathComponent("\(args.name).app")
        let contentsURL = appURL.appendingPathComponent("Contents")
        let macosURL = contentsURL.appendingPathComponent("MacOS")
        let resourcesURL = contentsURL.appendingPathComponent("Resources")

        if fm.fileExists(atPath: appURL.path) {
            try fm.removeItem(at: appURL)
        }
        for dir in [macosURL, resourcesURL] {
            try fm.createDirectory(at: dir, withIntermediateDirectories: true)
        }

        // Launcher
        let launcherURL = macosURL.appendingPathComponent("launcher")
        try launcherScript().write(to: launcherURL, atomically: true, encoding: .utf8)
        try setExecutable(at: launcherURL)

        // Info.plist
        let plistData = try PropertyListSerialization.data(
            fromPropertyList: buildPlist(hasIcon: iconURL != nil),
            format: .xml, options: 0
        )
        try plistData.write(to: contentsURL.appendingPathComponent("Info.plist"))

        // PkgInfo
        try "APPL????".write(
            to: contentsURL.appendingPathComponent("PkgInfo"),
            atomically: true, encoding: .utf8
        )

        // Icon
        if let iconURL = iconURL, fm.fileExists(atPath: iconURL.path) {
            try fm.copyItem(at: iconURL, to: resourcesURL.appendingPathComponent("icon.icns"))
        }

        return appURL
    }

    private func launcherScript() -> String {
        return """
        #!/bin/bash
        # Appify launcher — generated by appify v1.0.0
        # App  : \(args.name)
        # URL  : \(args.url)

        if command -v python3 &>/dev/null && python3 -c "import webview" 2>/dev/null; then
            exec python3 - <<'PYEOF'
        import webview
        window = webview.create_window(
            \"\(args.name.replacingOccurrences(of: "\"", with: "\\\""))\",
            \"\(args.url)\",
            width=\(args.width),
            height=\(args.height),
            resizable=True,
            min_size=(400, 300),
        )
        webview.start()
        PYEOF
        fi

        echo "pywebview not found — opening in browser instead."
        echo "Install it with: pip install pywebview"
        open "\(args.url)"
        """
    }

    private func buildPlist(hasIcon: Bool) -> [String: Any] {
        var plist: [String: Any] = [
            "CFBundleName": args.name,
            "CFBundleDisplayName": args.name,
            "CFBundleExecutable": "launcher",
            "CFBundleIdentifier": "com.appify.\(sanitizeBundleId(args.name))",
            "CFBundleInfoDictionaryVersion": "6.0",
            "CFBundlePackageType": "APPL",
            "CFBundleShortVersionString": "1.0",
            "CFBundleVersion": "1",
            "NSHighResolutionCapable": true,
            "LSMinimumSystemVersion": "13.0",
            "NSPrincipalClass": "NSApplication",
        ]
        if hasIcon { plist["CFBundleIconFile"] = "icon" }
        if args.menuBar { plist["LSUIElement"] = true }
        return plist
    }

    private func sanitizeBundleId(_ name: String) -> String {
        name.lowercased()
            .components(separatedBy: CharacterSet.alphanumerics.inverted)
            .filter { !$0.isEmpty }
            .joined(separator: "-")
    }

    private func setExecutable(at url: URL) throws {
        var attrs = try FileManager.default.attributesOfItem(atPath: url.path)
        let current = (attrs[.posixPermissions] as? Int) ?? 0o644
        attrs[.posixPermissions] = current | 0o111
        try FileManager.default.setAttributes(attrs, ofItemAtPath: url.path)
    }
}
